interface Presets {
  [key: string]: any
}

interface PresetPaths {
  [key: string]: string
}

export const presets: Presets = {}

interface GetPresetOptions {
  name?: string
  random?: boolean
  count?: number
}

const presetPaths: PresetPaths = {
  '07': './presets/07.json',
  '131': './presets/131.json',
  '132': './presets/132.json',
  '133': './presets/133.json',
  '134': './presets/134.json',
  '135': './presets/135.json',
  '136': './presets/136.json',
  '145': './presets/145.json',
  '305': './presets/305.json',
  '306': './presets/306.json',
  '333': './presets/333.json',
  '389': './presets/389.json',
  '3Dragons_rovastar-mineexploded': './presets/3Dragons_rovastar-mineexploded.json',
  '53': './presets/53.json',
  '54': './presets/54.json',
  '55': './presets/55.json',
  '56': './presets/56.json',
  '64': './presets/64.json',
  '67': './presets/67.json',
  '74': './presets/74.json',
  '79': './presets/79.json',
  '87': './presets/87.json',
  'A': './presets/A.json',
  'Aderrasi - Airhandler _Principle of Sharing_': './presets/Aderrasi - Airhandler _Principle of Sharing_.json',
  'Aderrasi - Ashes Of Air _Remix_': './presets/Aderrasi - Ashes Of Air _Remix_.json',
  'Aderrasi - Chromatic Abyss _Refined Abyss Mix_': './presets/Aderrasi - Chromatic Abyss _Refined Abyss Mix_.json',
  'Aderrasi - Chromatic Abyss _The Other Side_': './presets/Aderrasi - Chromatic Abyss _The Other Side_.json',
  'Aderrasi - Graft _First Rate Heart_': './presets/Aderrasi - Graft _First Rate Heart_.json',
  'Aderrasi - Horvath_s Holistic Abyss': './presets/Aderrasi - Horvath_s Holistic Abyss.json',
  'Aderrasi - Potion of Spirits': './presets/Aderrasi - Potion of Spirits.json',
  'Aderrasi-crossroads_twitchmix_': './presets/Aderrasi-crossroads_twitchmix_.json',
  'Aderrasi-spirits': './presets/Aderrasi-spirits.json',
  'AkashaDude _ Geiss - DeltaTango': './presets/AkashaDude _ Geiss - DeltaTango.json',
  'amandio c  - tricks with ellipses 1': './presets/amandio c  - tricks with ellipses 1.json',
  'amandio c  - tricks with ellipses 2': './presets/amandio c  - tricks with ellipses 2.json',
  'amandio c - circles intersection 1': './presets/amandio c - circles intersection 1.json',
  'amandio c - circles intersection 2': './presets/amandio c - circles intersection 2.json',
  'amandio c - circles intersection 3': './presets/amandio c - circles intersection 3.json',
  'amandio c - circles intersection 6': './presets/amandio c - circles intersection 6.json',
  'amandio c - dark side of the sun 1': './presets/amandio c - dark side of the sun 1.json',
  'amandio c - dark side of the sun 2': './presets/amandio c - dark side of the sun 2.json',
  'amandio c - ecllipse 2': './presets/amandio c - ecllipse 2.json',
  'amandio c - embrace 01': './presets/amandio c - embrace 01.json',
  'amandio c - embrace 02': './presets/amandio c - embrace 02.json',
  'amandio c - embrace 03': './presets/amandio c - embrace 03.json',
  'amandio c - embrace 05': './presets/amandio c - embrace 05.json',
  'amandio c - embrace 07': './presets/amandio c - embrace 07.json',
  'amandio c - feeling well 2': './presets/amandio c - feeling well 2.json',
  'amandio c - feeling well 3': './presets/amandio c - feeling well 3.json',
  'amandio c - feeling well 4': './presets/amandio c - feeling well 4.json',
  'amandio c - feeling well 5': './presets/amandio c - feeling well 5.json',
  'amandio c - feeling well 7': './presets/amandio c - feeling well 7.json',
  'amandio c - feeling well': './presets/amandio c - feeling well.json',
  'amandio c - future engines': './presets/amandio c - future engines.json',
  'Amandio C - Goldline _fireworks_': './presets/Amandio C - Goldline _fireworks_.json',
  'amandio c - IFS 01': './presets/amandio c - IFS 01.json',
  'amandio c - interference pattern 1': './presets/amandio c - interference pattern 1.json',
  'amandio c - interference pattern 2': './presets/amandio c - interference pattern 2.json',
  'amandio c - interference pattern 3': './presets/amandio c - interference pattern 3.json',
  'amandio c - interference pattern 4': './presets/amandio c - interference pattern 4.json',
  'amandio c - iterative - spirals': './presets/amandio c - iterative - spirals.json',
  'amandio c - iterative - squares 1': './presets/amandio c - iterative - squares 1.json',
  'amandio c - iterative - squares 2': './presets/amandio c - iterative - squares 2.json',
  'amandio c - iterative - squares 3': './presets/amandio c - iterative - squares 3.json',
  'amandio c - iterative - squares 4': './presets/amandio c - iterative - squares 4.json',
  'amandio c - iterative - tendrils': './presets/amandio c - iterative - tendrils.json',
  'amandio c - magnetosphere': './presets/amandio c - magnetosphere.json',
  'amandio c - new life a': './presets/amandio c - new life a.json',
  'amandio c - new life': './presets/amandio c - new life.json',
  'amandio c - odd star': './presets/amandio c - odd star.json',
  'amandio c - odd twins': './presets/amandio c - odd twins.json',
  'amandio c - Orbitin_ around 3': './presets/amandio c - Orbitin_ around 3.json',
  'amandio c - pulse': './presets/amandio c - pulse.json',
  'amandio c - salty beats': './presets/amandio c - salty beats.json',
  'amandio c - salty bits - 5': './presets/amandio c - salty bits - 5.json',
  'amandio c - secret garden 3': './presets/amandio c - secret garden 3.json',
  'amandio c - secret garden 4': './presets/amandio c - secret garden 4.json',
  'amandio c - secret garden 5': './presets/amandio c - secret garden 5.json',
  'amandio c - secret garden 6': './presets/amandio c - secret garden 6.json',
  'amandio c - secret garden 7': './presets/amandio c - secret garden 7.json',
  'amandio c - small life _goes disco_': './presets/amandio c - small life _goes disco_.json',
  'amandio c - the green machine 4 - radial': './presets/amandio c - the green machine 4 - radial.json',
  'amandio c - water ripples - 2D': './presets/amandio c - water ripples - 2D.json',
  'amandio c - woofer': './presets/amandio c - woofer.json',
  'Awakening': './presets/Awakening.json',
  'baked - Chinese Fingerbang': './presets/baked - Chinese Fingerbang.json',
  'bdrv - comet5fhk pasta2ffsfghgjh': './presets/bdrv - comet5fhk pasta2ffsfghgjh.json',
  'bdrv - comet5fhk pasta2g framespace invader ': './presets/bdrv - comet5fhk pasta2g framespace invader .json',
  'bdrv - monster wave': './presets/bdrv - monster wave.json',
  'Bdrv Aderrasi - Inhuman Emotion bw5': './presets/Bdrv Aderrasi - Inhuman Emotion bw5.json',
  'BDRV Aderrasi - Negative Sun _Haze Star_BDRV et  AL  rmxmix3': './presets/BDRV Aderrasi - Negative Sun _Haze Star_BDRV et  AL  rmxmix3.json',
  'Bdrv Aderrasi - Negative Sun _Haze Star_BDRV et  AL  rmxmix4': './presets/Bdrv Aderrasi - Negative Sun _Haze Star_BDRV et  AL  rmxmix4.json',
  'BDRV et AL shifter - tumbling cubes 5': './presets/BDRV et AL shifter - tumbling cubes 5.json',
  'bdrv _ al Rovastar - Explosive Minds Bug Mix wait a moment  rmx': './presets/bdrv _ al Rovastar - Explosive Minds Bug Mix wait a moment  rmx.json',
  'bdrv _ al shifter - feathers _angel wings__phat_remix4 BDRV et  AL  rmx ii': './presets/bdrv _ al shifter - feathers _angel wings__phat_remix4 BDRV et  AL  rmx ii.json',
  'bdrv _ al shifter - phasm mx': './presets/bdrv _ al shifter - phasm mx.json',
  'Benjam - Dust on the Lens': './presets/Benjam - Dust on the Lens.json',
  'Benjam - Fractal Timepiece': './presets/Benjam - Fractal Timepiece.json',
  'Benjam _ Zylot - Dust on the Lens _Light of the Ancient Ones mix_': './presets/Benjam _ Zylot - Dust on the Lens _Light of the Ancient Ones mix_.json',
  'beta106ain-sunrays': './presets/beta106ain-sunrays.json',
  'beta106i - Airhandler _Last Breath - Calm Features_': './presets/beta106i - Airhandler _Last Breath - Calm Features_.json',
  'beta106i - Airhandler _Last Breath - Clam Handler_': './presets/beta106i - Airhandler _Last Breath - Clam Handler_.json',
  'beta106i - Airhandler _Last Breath - Clam_': './presets/beta106i - Airhandler _Last Breath - Clam_.json',
  'beta106i - Airhandler _Last Breath - Crab Handler_': './presets/beta106i - Airhandler _Last Breath - Crab Handler_.json',
  'beta106i - Airhandler _Last Breath - Crab Hand_': './presets/beta106i - Airhandler _Last Breath - Crab Hand_.json',
  'beta106i - Airhandler _Last Breath - Demon Evolution_': './presets/beta106i - Airhandler _Last Breath - Demon Evolution_.json',
  'beta106i - Airhandler _Last Breath - Dust God_': './presets/beta106i - Airhandler _Last Breath - Dust God_.json',
  'beta106i - Airhandler _Last Breath - Eden_': './presets/beta106i - Airhandler _Last Breath - Eden_.json',
  'beta106i - Airhandler _Last Breath - Justice_': './presets/beta106i - Airhandler _Last Breath - Justice_.json',
  'beta106i - Airhandler _Last Breath_': './presets/beta106i - Airhandler _Last Breath_.json',
  'beta106i - Airhandler _Looking Into You - Beholder_': './presets/beta106i - Airhandler _Looking Into You - Beholder_.json',
  'beta106i - Airhandler _Principle of Airworks_': './presets/beta106i - Airhandler _Principle of Airworks_.json',
  'beta106i - Airhandler _Radial Dreamers - Nightmare_': './presets/beta106i - Airhandler _Radial Dreamers - Nightmare_.json',
  'beta106i - Airhandler _Radial Dreamers_': './presets/beta106i - Airhandler _Radial Dreamers_.json',
  'beta106i - Antidote _Crying Pan_': './presets/beta106i - Antidote _Crying Pan_.json',
  'beta106i - Antidote _Sugar Flood_': './presets/beta106i - Antidote _Sugar Flood_.json',
  'beta106i - Antidote _Sugar Wave_': './presets/beta106i - Antidote _Sugar Wave_.json',
  'beta106i - Arise_ _Padded_': './presets/beta106i - Arise_ _Padded_.json',
  'beta106i - Ashes of Air _Molecular Level_': './presets/beta106i - Ashes of Air _Molecular Level_.json',
  'beta106i - Ashes of Air _Strings_': './presets/beta106i - Ashes of Air _Strings_.json',
  'beta106i - Brilliance _Mind Consuming Substance_': './presets/beta106i - Brilliance _Mind Consuming Substance_.json',
  'beta106i - Contortion _Wind Up_': './presets/beta106i - Contortion _Wind Up_.json',
  'beta106i - Corners of the Globe': './presets/beta106i - Corners of the Globe.json',
  'beta106i - Demon Heavy': './presets/beta106i - Demon Heavy.json',
  'beta106i - Eruption _Organic Lattice_': './presets/beta106i - Eruption _Organic Lattice_.json',
  'beta106i - Eruption _Organic Soup_': './presets/beta106i - Eruption _Organic Soup_.json',
  'beta106i - Grief Adjustment _Chi_': './presets/beta106i - Grief Adjustment _Chi_.json',
  'beta106i - Gross Product _The Fractal Twins_': './presets/beta106i - Gross Product _The Fractal Twins_.json',
  'beta106i - Hard Drink _Gin and Kava_': './presets/beta106i - Hard Drink _Gin and Kava_.json',
  'beta106i - Jupiter _Divine Lances_': './presets/beta106i - Jupiter _Divine Lances_.json',
  'beta106i - Molten Core': './presets/beta106i - Molten Core.json',
  'beta106i - Negative Sun _Black Hole_': './presets/beta106i - Negative Sun _Black Hole_.json',
  'beta106i - Negative Sun _Haze Star_': './presets/beta106i - Negative Sun _Haze Star_.json',
  'beta106i - Old Myths and Fairytales': './presets/beta106i - Old Myths and Fairytales.json',
  'beta106i - Origins of Life _All Human_': './presets/beta106i - Origins of Life _All Human_.json',
  'beta106i - Potion of Agility': './presets/beta106i - Potion of Agility.json',
  'beta106i - Potion of Air': './presets/beta106i - Potion of Air.json',
  'beta106i - Potion of Ink': './presets/beta106i - Potion of Ink.json',
  'beta106i - Potion of Life': './presets/beta106i - Potion of Life.json',
  'beta106i - Potion of Resurrection': './presets/beta106i - Potion of Resurrection.json',
  'beta106i - Potion of Smoke': './presets/beta106i - Potion of Smoke.json',
  'beta106i - Potion': './presets/beta106i - Potion.json',
  'beta106i - Quantum Variants _Mystery_': './presets/beta106i - Quantum Variants _Mystery_.json',
  'beta106i - Songflower _Ice Flower_': './presets/beta106i - Songflower _Ice Flower_.json',
  'beta106i - Straight Tropical Coal _Hypnotricks Stable Mix_': './presets/beta106i - Straight Tropical Coal _Hypnotricks Stable Mix_.json',
  'beta106i - Superstrings': './presets/beta106i - Superstrings.json',
  'beta106i - Trickshot _No Man_s Land_': './presets/beta106i - Trickshot _No Man_s Land_.json',
  'beta106i - Zap _Jelly Mix_': './presets/beta106i - Zap _Jelly Mix_.json',
  'beta106Random - Turbulence Sandwich': './presets/beta106Random - Turbulence Sandwich.json',
  'Blastofftek - Plasma Revisited': './presets/Blastofftek - Plasma Revisited.json',
  'Bmelgren - Acid Iris': './presets/Bmelgren - Acid Iris.json',
  'Bmelgren - Getter Sun 1': './presets/Bmelgren - Getter Sun 1.json',
  'bmelgren - Getter Sun tweek 1': './presets/bmelgren - Getter Sun tweek 1.json',
  'bmelgren - Getter Sun tweek 2': './presets/bmelgren - Getter Sun tweek 2.json',
  'bmelgren - Getter Sun tweek 3': './presets/bmelgren - Getter Sun tweek 3.json',
  'Bmelgren - Liquirdo 2': './presets/Bmelgren - Liquirdo 2.json',
  'bmelgren - Liqurido': './presets/bmelgren - Liqurido.json',
  'bmelgren - Liqurido2': './presets/bmelgren - Liqurido2.json',
  'Bmelgren - Penultimate Neural Slipstream 2': './presets/Bmelgren - Penultimate Neural Slipstream 2.json',
  'bmelgren - Returning To Rovastar_s Return To The Source': './presets/bmelgren - Returning To Rovastar_s Return To The Source.json',
  'Bmelgren - Shimmer N Shine': './presets/Bmelgren - Shimmer N Shine.json',
  'Bmelgren - Tonic': './presets/Bmelgren - Tonic.json',
  'Bmelgren _ Krash - Rainbow Orb Peacock _Lonely Signal Gone Mad Mix_': './presets/Bmelgren _ Krash - Rainbow Orb Peacock _Lonely Signal Gone Mad Mix_.json',
  'Bmelgren _ Rovastar - Schisathing Coalescence 2': './presets/Bmelgren _ Rovastar - Schisathing Coalescence 2.json',
  'Bmelgren _ Rovastar - Throbbing Northern Lights': './presets/Bmelgren _ Rovastar - Throbbing Northern Lights.json',
  'Bmelgren-angeldreams': './presets/Bmelgren-angeldreams.json',
  'Bmelgren-morpherous3': './presets/Bmelgren-morpherous3.json',
  'Bmelgren_krash-rainbo_unknowablemix1_': './presets/Bmelgren_krash-rainbo_unknowablemix1_.json',
  'Bmelgren_krash-schizophrenia2': './presets/Bmelgren_krash-schizophrenia2.json',
  'Bmelgren_Rovastar-Jester_sAwakening_R': './presets/Bmelgren_Rovastar-Jester_sAwakening_R.json',
  'Bmelgren_rovastar-schisathing5': './presets/Bmelgren_rovastar-schisathing5.json',
  'Bmelgren_Rovastar-SchisathingCoalesce': './presets/Bmelgren_Rovastar-SchisathingCoalesce.json',
  'Bmelgren_unchained-amb_mythicrainmix_': './presets/Bmelgren_unchained-amb_mythicrainmix_.json',
  'Bmelgren_unchained-a_spinningrainmix_': './presets/Bmelgren_unchained-a_spinningrainmix_.json',
  'Bmelgren_unchained-effort_remix_': './presets/Bmelgren_unchained-effort_remix_.json',
  'Bmelgren_unchained-roadkilldin_remix_': './presets/Bmelgren_unchained-roadkilldin_remix_.json',
  'Bmelgren_unchained_spacetimeblipknot_': './presets/Bmelgren_unchained_spacetimeblipknot_.json',
  'Border-magic': './presets/Border-magic.json',
  'Boz - All Night Cashews': './presets/Boz - All Night Cashews.json',
  'Boz - Buckwild _Sheltered Mix_': './presets/Boz - Buckwild _Sheltered Mix_.json',
  'Boz-buckwild': './presets/Boz-buckwild.json',
  'BrainStain- boiling-mix2_redi jedi full carb mix_': './presets/BrainStain- boiling-mix2_redi jedi full carb mix_.json',
  'BrainStain-Blackwidow': './presets/BrainStain-Blackwidow.json',
  'BrainStain-boiling-comfortably numb-mix': './presets/BrainStain-boiling-comfortably numb-mix.json',
  'BrainStain-fish on': './presets/BrainStain-fish on.json',
  'BrainStain-re entry': './presets/BrainStain-re entry.json',
  'BrainStain-sunrays': './presets/BrainStain-sunrays.json',
  'Brownian Bass': './presets/Brownian Bass.json',
  'CatalystTheElder - Hal_s_Nigtmare_Halo_Mix': './presets/CatalystTheElder - Hal_s_Nigtmare_Halo_Mix.json',
  'cellular growth': './presets/cellular growth.json',
  'Che - Barcode Infidelity _Deep Pricelist Mix_': './presets/Che - Barcode Infidelity _Deep Pricelist Mix_.json',
  'Che-slowmotion': './presets/Che-slowmotion.json',
  'Chemlock - Berry Maddog 20-20': './presets/Chemlock - Berry Maddog 20-20.json',
  'Chemlock - Lily Hallucinogen _Geiss - Feedback_': './presets/Chemlock - Lily Hallucinogen _Geiss - Feedback_.json',
  'Chemlock - Metal Mud': './presets/Chemlock - Metal Mud.json',
  'Compelling Vision': './presets/Compelling Vision.json',
  'Cosmic Eclipse Storm': './presets/Cosmic Eclipse Storm.json',
  'Cosmic Eclipse': './presets/Cosmic Eclipse.json',
  'Dark One - Clouds': './presets/Dark One - Clouds.json',
  'Dark One - Enni Cened Silmarilli': './presets/Dark One - Enni Cened Silmarilli.json',
  'Dark One - Happy Sad Daisy': './presets/Dark One - Happy Sad Daisy.json',
  'Dbleja - Escape _Blue Mix_': './presets/Dbleja - Escape _Blue Mix_.json',
  'Dbleja - Escape _Red Mix_': './presets/Dbleja - Escape _Red Mix_.json',
  'Dbleja - Escape _White Mix_': './presets/Dbleja - Escape _White Mix_.json',
  'Dbleja - Horizontology _Blue Mix_': './presets/Dbleja - Horizontology _Blue Mix_.json',
  'Dbleja - Horizontology _Red Mix_': './presets/Dbleja - Horizontology _Red Mix_.json',
  'Dbleja - Horizontology _White Mix_': './presets/Dbleja - Horizontology _White Mix_.json',
  'Dbleja - Hovering Over Mars': './presets/Dbleja - Hovering Over Mars.json',
  'Dbleja - Hovering Over Neptune': './presets/Dbleja - Hovering Over Neptune.json',
  'Dbleja - Hovering Over Pluto': './presets/Dbleja - Hovering Over Pluto.json',
  'Dbleja - Inside The Tree _Blue Mix_': './presets/Dbleja - Inside The Tree _Blue Mix_.json',
  'Dbleja - Inside The Tree _Red Mix_': './presets/Dbleja - Inside The Tree _Red Mix_.json',
  'Dbleja - Inside The Tree _White Mix_': './presets/Dbleja - Inside The Tree _White Mix_.json',
  'Dbleja - Rings Of Saturn': './presets/Dbleja - Rings Of Saturn.json',
  'Eos-skylighta1_musicwarpswitch_': './presets/Eos-skylighta1_musicwarpswitch_.json',
  'Eos-skylighta2_tripcolors_': './presets/Eos-skylighta2_tripcolors_.json',
  'Eos-sparkcphatjestermix': './presets/Eos-sparkcphatjestermix.json',
  'Eosphat-chasers11sentinelc': './presets/Eosphat-chasers11sentinelc.json',
  'Eosphat-chasers18hallway': './presets/Eosphat-chasers18hallway.json',
  'Eosphat-chasers21primordialsoup': './presets/Eosphat-chasers21primordialsoup.json',
  'Eosphat-chasers22feedmebrains': './presets/Eosphat-chasers22feedmebrains.json',
  'Eosphat-chasers23feedmebrainsv2': './presets/Eosphat-chasers23feedmebrainsv2.json',
  'Esotic vs Rozzor - Pixie Party Light _No Wave Invasion_ Mandala Chill Red Yellow': './presets/Esotic vs Rozzor - Pixie Party Light _No Wave Invasion_ Mandala Chill Red Yellow.json',
  'Esotic vs Rozzor - Pixie Party Light _No Wave Invasion_ Mandala': './presets/Esotic vs Rozzor - Pixie Party Light _No Wave Invasion_ Mandala.json',
  'Esotic _ Rozzer - Hippie Hypnotizer': './presets/Esotic _ Rozzer - Hippie Hypnotizer.json',
  'Esotic _ Rozzer - Now And Later': './presets/Esotic _ Rozzer - Now And Later.json',
  'Esotic _ Rozzer - Pixie Party Light _With Liquid Refreshment_ _Bonus Round Mix_': './presets/Esotic _ Rozzer - Pixie Party Light _With Liquid Refreshment_ _Bonus Round Mix_.json',
  'Esotic _ Rozzer - The Dark Side Of My Moon': './presets/Esotic _ Rozzer - The Dark Side Of My Moon.json',
  'Esotic _ Rozzor - Pixie Party Light __No Wave Invasion_ Inner Space 2 Mix_': './presets/Esotic _ Rozzor - Pixie Party Light __No Wave Invasion_ Inner Space 2 Mix_.json',
  'Esotic _ Rozzor - Pixie Party Light __No Wave Invasion_ Mandala Chill Mix_': './presets/Esotic _ Rozzor - Pixie Party Light __No Wave Invasion_ Mandala Chill Mix_.json',
  'Evil02 - Liquid Lighting': './presets/Evil02 - Liquid Lighting.json',
  'EvilJim - Ice Drops': './presets/EvilJim - Ice Drops.json',
  'EvilJim - _07 Supernova': './presets/EvilJim - _07 Supernova.json',
  'EvilJim - _11 Ice Drops': './presets/EvilJim - _11 Ice Drops.json',
  'EvilJim - _17 Travelling backwards in a Tunnel of Light': './presets/EvilJim - _17 Travelling backwards in a Tunnel of Light.json',
  'EvilJim - _19 Space Voyage': './presets/EvilJim - _19 Space Voyage.json',
  'EvilJim - _26 I see Light_': './presets/EvilJim - _26 I see Light_.json',
  'fiberglass-Fvese-remix': './presets/fiberglass-Fvese-remix.json',
  'Fireball': './presets/Fireball.json',
  'fiShbRaiN - betelguese _hyperdrive remix_': './presets/fiShbRaiN - betelguese _hyperdrive remix_.json',
  'fiShbRaiN - betelguese': './presets/fiShbRaiN - betelguese.json',
  'fiShbRaiN - blueprint': './presets/fiShbRaiN - blueprint.json',
  'fiShbRaiN - city slicker': './presets/fiShbRaiN - city slicker.json',
  'fiShbRaiN - crystal glasses': './presets/fiShbRaiN - crystal glasses.json',
  'fiShbRaiN - cthulhus asshole _bad breakfast remix_': './presets/fiShbRaiN - cthulhus asshole _bad breakfast remix_.json',
  'fiShbRaiN - cthulhus asshole': './presets/fiShbRaiN - cthulhus asshole.json',
  'fiShbRaiN - evolution _3d__phat_edit_v2': './presets/fiShbRaiN - evolution _3d__phat_edit_v2.json',
  'fiShbRaiN - gandalf does it best _pipeweed remix v2__phat_rose_mix': './presets/fiShbRaiN - gandalf does it best _pipeweed remix v2__phat_rose_mix.json',
  'fiShbRaiN - gandalf does it best _pipeweed remix v2__Phat_slooow_edit': './presets/fiShbRaiN - gandalf does it best _pipeweed remix v2__Phat_slooow_edit.json',
  'fiShbRaiN - hexadecimal theory': './presets/fiShbRaiN - hexadecimal theory.json',
  'fiShbRaiN - molecule mind': './presets/fiShbRaiN - molecule mind.json',
  'fiShbRaiN - one step beyond _alien remix_': './presets/fiShbRaiN - one step beyond _alien remix_.json',
  'fiShbRaiN - plasma temptation': './presets/fiShbRaiN - plasma temptation.json',
  'fiShbRaiN - psychotic meltdown _peyote mix_': './presets/fiShbRaiN - psychotic meltdown _peyote mix_.json',
  'fiShbRaiN - psychotic meltdown': './presets/fiShbRaiN - psychotic meltdown.json',
  'fiShbRaiN - quark matrix': './presets/fiShbRaiN - quark matrix.json',
  'fiShbRaiN - submarine': './presets/fiShbRaiN - submarine.json',
  'fiShbRaiN - swarm _3d_': './presets/fiShbRaiN - swarm _3d_.json',
  'fiShbRaiN - swarming glory suksma shapes': './presets/fiShbRaiN - swarming glory suksma shapes.json',
  'fiShbRaiN - swarming glory _angry remix_': './presets/fiShbRaiN - swarming glory _angry remix_.json',
  'fiShbRaiN - swarming glory _geomancy remix_': './presets/fiShbRaiN - swarming glory _geomancy remix_.json',
  'fiShbRaiN - swarming glory _spiral remix_': './presets/fiShbRaiN - swarming glory _spiral remix_.json',
  'fiShbRaiN - swarming glory': './presets/fiShbRaiN - swarming glory.json',
  'fiShbRaiN - the adventures of prismo jenkins': './presets/fiShbRaiN - the adventures of prismo jenkins.json',
  'fiShbRaiN - toffee cream and icing sugar': './presets/fiShbRaiN - toffee cream and icing sugar.json',
  'fiShbRaiN - when coathangers dream_phat_edit': './presets/fiShbRaiN - when coathangers dream_phat_edit.json',
  'fiShbRaiN - when robots take over the world': './presets/fiShbRaiN - when robots take over the world.json',
  'fiShbRaiN - white scream firefly': './presets/fiShbRaiN - white scream firefly.json',
  'fiShbRaiN - witchcraft _alcoholic remix_': './presets/fiShbRaiN - witchcraft _alcoholic remix_.json',
  'fiShbRaiN - witchcraft _DMT remix_': './presets/fiShbRaiN - witchcraft _DMT remix_.json',
  'fiShbRaiN - witchcraft _metropolis remix_': './presets/fiShbRaiN - witchcraft _metropolis remix_.json',
  'fiShbRaiN - witchcraft _metropolish remix_ - test': './presets/fiShbRaiN - witchcraft _metropolish remix_ - test.json',
  'fiShbRaiN - witchcraft _metropolish remix_': './presets/fiShbRaiN - witchcraft _metropolish remix_.json',
  'fiShbRaiN - witchcraft _necromancer remix_ - busy': './presets/fiShbRaiN - witchcraft _necromancer remix_ - busy.json',
  'fiShbRaiN - witchcraft _necromancer remix_': './presets/fiShbRaiN - witchcraft _necromancer remix_.json',
  'fiShbRaiN - witchcraft _necromancer remix__phat_edit': './presets/fiShbRaiN - witchcraft _necromancer remix__phat_edit.json',
  'fiShbRaiN - witchcraft _necromancer remix__phat_edit_v2': './presets/fiShbRaiN - witchcraft _necromancer remix__phat_edit_v2.json',
  'fiShbRaiN - witchcraft _necromancer remix__phat_edit_v3': './presets/fiShbRaiN - witchcraft _necromancer remix__phat_edit_v3.json',
  'fiShbRaiN - witchcraft _neuromancer remix_': './presets/fiShbRaiN - witchcraft _neuromancer remix_.json',
  'fiShbRaiN - witchcraft _ritual dance remix_': './presets/fiShbRaiN - witchcraft _ritual dance remix_.json',
  'fiShbRaiN - witchcraft _sorcery remix_': './presets/fiShbRaiN - witchcraft _sorcery remix_.json',
  'fiShbRaiN - witchcraft': './presets/fiShbRaiN - witchcraft.json',
  'Flexi - dont ask': './presets/Flexi - dont ask.json',
  'Flexi - hallucination _1': './presets/Flexi - hallucination _1.json',
  'Flexi - leaving colors - crazy cogitations centrifuge': './presets/Flexi - leaving colors - crazy cogitations centrifuge.json',
  'Flexi - leaving colors - magic happened to my wallpaper': './presets/Flexi - leaving colors - magic happened to my wallpaper.json',
  'Flexi - _0_ - rotating per-pixel tutorial': './presets/Flexi - _0_ - rotating per-pixel tutorial.json',
  'Fvese - The Tunnel _Final Stage Mix_': './presets/Fvese - The Tunnel _Final Stage Mix_.json',
  'Fvese - Zoom Effects _Remix 3_': './presets/Fvese - Zoom Effects _Remix 3_.json',
  'Fvese-mvfun1': './presets/Fvese-mvfun1.json',
  'Fvese-mvfun2': './presets/Fvese-mvfun2.json',
  'Fvese-mvfun3': './presets/Fvese-mvfun3.json',
  'Fvese-mvfun4': './presets/Fvese-mvfun4.json',
  'Fvese-snowflakelike2': './presets/Fvese-snowflakelike2.json',
  'Geiss - 3D - Cosmic Dust': './presets/Geiss - 3D - Cosmic Dust.json',
  'Geiss - 3D - Luz': './presets/Geiss - 3D - Luz.json',
  'Geiss - 3D - Shockwaves': './presets/Geiss - 3D - Shockwaves.json',
  'Geiss - Bipolar 3': './presets/Geiss - Bipolar 3.json',
  'Geiss - Bipolar 4': './presets/Geiss - Bipolar 4.json',
  'Geiss - Bipolar X': './presets/Geiss - Bipolar X.json',
  'Geiss - Bipolar _Overdrive Remix_': './presets/Geiss - Bipolar _Overdrive Remix_.json',
  'Geiss - Casino': './presets/Geiss - Casino.json',
  'Geiss - Cepiasound': './presets/Geiss - Cepiasound.json',
  'Geiss - City At Night': './presets/Geiss - City At Night.json',
  'Geiss - Cosmic Dust 1': './presets/Geiss - Cosmic Dust 1.json',
  'Geiss - Drift': './presets/Geiss - Drift.json',
  'Geiss - Eggs': './presets/Geiss - Eggs.json',
  'Geiss - Flower Blossom': './presets/Geiss - Flower Blossom.json',
  'Geiss - Flower': './presets/Geiss - Flower.json',
  'Geiss - Galaxy 1': './presets/Geiss - Galaxy 1.json',
  'Geiss - Happy Drops': './presets/Geiss - Happy Drops.json',
  'Geiss - Luz': './presets/Geiss - Luz.json',
  'Geiss - Many Colors 1': './presets/Geiss - Many Colors 1.json',
  'Geiss - Many Colors 2': './presets/Geiss - Many Colors 2.json',
  'Geiss - Mega Swirl 3': './presets/Geiss - Mega Swirl 3.json',
  'Geiss - Monotone Ripples': './presets/Geiss - Monotone Ripples.json',
  'Geiss - Swirlie 5': './presets/Geiss - Swirlie 5.json',
  'Geiss - Three And A Half Kinds Of Amphetamines': './presets/Geiss - Three And A Half Kinds Of Amphetamines.json',
  'Geiss - Vapor Echo': './presets/Geiss - Vapor Echo.json',
  'Geiss and Rovastar - Many More Colours': './presets/Geiss and Rovastar - Many More Colours.json',
  'Geiss _ TobiasWolfBoi - Cataract Slipstream': './presets/Geiss _ TobiasWolfBoi - Cataract Slipstream.json',
  'Goody - LSD Zoomtunnel': './presets/Goody - LSD Zoomtunnel.json',
  'Goody - Unstable Sonic Reactor - Final': './presets/Goody - Unstable Sonic Reactor - Final.json',
  'goody_3__ hexcollie_ fed_2__ flexi_2_ - _8': './presets/goody_3__ hexcollie_ fed_2__ flexi_2_ - _8.json',
  'goody_3__ hexcollie_2__ fed_2__ flexi_2_ - _9 _sorry for demolishing your code_': './presets/goody_3__ hexcollie_2__ fed_2__ flexi_2_ - _9 _sorry for demolishing your code_.json',
  'goody_3__ hexcollie_2__ fed_2__ flexi_3_ - _10 _face your child_': './presets/goody_3__ hexcollie_2__ fed_2__ flexi_3_ - _10 _face your child_.json',
  'goody_3__ hexcollie_3__ fed_2__ flexi_3_ - _11 _bulk_': './presets/goody_3__ hexcollie_3__ fed_2__ flexi_3_ - _11 _bulk_.json',
  'goody_4__ hexcollie_3__ fed_2__ flexi_3_ - _12 _less spasticity and fps tweak - fixed twitchy wave__': './presets/goody_4__ hexcollie_3__ fed_2__ flexi_3_ - _12 _less spasticity and fps tweak - fixed twitchy wave__.json',
  'goody_4__ hexcollie_3__ fed_2__ flexi_3__ stahlregen _1_ - _13': './presets/goody_4__ hexcollie_3__ fed_2__ flexi_3__ stahlregen _1_ - _13.json',
  'Goody_s LSD Zoomtunnel _sharp_': './presets/Goody_s LSD Zoomtunnel _sharp_.json',
  'Goody_s LSD Zoomtunnel': './presets/Goody_s LSD Zoomtunnel.json',
  'Goody_s Thing Which Dwells Between Worlds': './presets/Goody_s Thing Which Dwells Between Worlds.json',
  'Goody_s Unstable Sonic Reactor _Inside of it all remix - aspect fix_': './presets/Goody_s Unstable Sonic Reactor _Inside of it all remix - aspect fix_.json',
  'Goody_s Unstable Sonic Reactor _Inside of it all remix_': './presets/Goody_s Unstable Sonic Reactor _Inside of it all remix_.json',
  'Goody_s Unstable Sonic Reactor _Reality Binding remix_': './presets/Goody_s Unstable Sonic Reactor _Reality Binding remix_.json',
  'Goody_s Unstable Sonic Reactor': './presets/Goody_s Unstable Sonic Reactor.json',
  'GreatWho - Lasershow': './presets/GreatWho - Lasershow.json',
  'Happening': './presets/Happening.json',
  'heavenly eye': './presets/heavenly eye.json',
  'Hexcollie - Abyssal Dreamscape Nightshade Twist': './presets/Hexcollie - Abyssal Dreamscape Nightshade Twist.json',
  'Hexcollie - Abyssal Dreamscape': './presets/Hexcollie - Abyssal Dreamscape.json',
  'hexcollie - Alex2': './presets/hexcollie - Alex2.json',
  'Hexcollie - Amorphous Magic carpet': './presets/Hexcollie - Amorphous Magic carpet.json',
  'hexcollie - Black Hole': './presets/hexcollie - Black Hole.json',
  'hexcollie - Blooming Squid': './presets/hexcollie - Blooming Squid.json',
  'Hexcollie - Bottlecap': './presets/Hexcollie - Bottlecap.json',
  'Hexcollie - Curly Que _1_': './presets/Hexcollie - Curly Que _1_.json',
  'Hexcollie - Curly Que': './presets/Hexcollie - Curly Que.json',
  'Hexcollie - Demonic Afterimages': './presets/Hexcollie - Demonic Afterimages.json',
  'hexcollie - Dizzy Spell4 Hypnotwrilic': './presets/hexcollie - Dizzy Spell4 Hypnotwrilic.json',
  'Hexcollie - do the twist': './presets/Hexcollie - do the twist.json',
  'hexcollie - DownwardSpiral': './presets/hexcollie - DownwardSpiral.json',
  'Hexcollie - Duality': './presets/Hexcollie - Duality.json',
  'hexcollie - Falconers eye': './presets/hexcollie - Falconers eye.json',
  'Hexcollie - First': './presets/Hexcollie - First.json',
  'Hexcollie - hairy colors': './presets/Hexcollie - hairy colors.json',
  'Hexcollie - K Hole2': './presets/Hexcollie - K Hole2.json',
  'Hexcollie - Novocaine for the soul': './presets/Hexcollie - Novocaine for the soul.json',
  'Hexcollie - Now thats a fucking K hole _personal mash_': './presets/Hexcollie - Now thats a fucking K hole _personal mash_.json',
  'Hexcollie - one more Lotus plumage ': './presets/Hexcollie - one more Lotus plumage .json',
  'Hexcollie - pearl': './presets/Hexcollie - pearl.json',
  'Hexcollie - Psychadelic Glue Sniffin Hillbillies the 2nd _personal mash_': './presets/Hexcollie - Psychadelic Glue Sniffin Hillbillies the 2nd _personal mash_.json',
  'hexcollie - soul snatcher further in to space': './presets/hexcollie - soul snatcher further in to space.json',
  'Hexcollie - Swaying Escher Trance ': './presets/Hexcollie - Swaying Escher Trance .json',
  'Hexcollie - This is where we begin stripped': './presets/Hexcollie - This is where we begin stripped.json',
  'Hexcollie - This is where we begin Without direction': './presets/Hexcollie - This is where we begin Without direction.json',
  'Hexcollie - Tommy the Cat _personal mash_': './presets/Hexcollie - Tommy the Cat _personal mash_.json',
  'Hexcollie - Trajic Simplicity': './presets/Hexcollie - Trajic Simplicity.json',
  'Hexcollie - Ultra blackhole sun': './presets/Hexcollie - Ultra blackhole sun.json',
  'Hexcollie - Ultra color twist': './presets/Hexcollie - Ultra color twist.json',
  'Hexcollie - Ultra daze2': './presets/Hexcollie - Ultra daze2.json',
  'Hexcollie - Unreal': './presets/Hexcollie - Unreal.json',
  'Hexcollie_ Geiss n Flexi - An important part of my collective brain is missing': './presets/Hexcollie_ Geiss n Flexi - An important part of my collective brain is missing.json',
  'Hexcollie_ Idiot n Inventive Software - Another alien to add to the list': './presets/Hexcollie_ Idiot n Inventive Software - Another alien to add to the list.json',
  'Hexcollie_ Krash_ Inventive software n Pithlit - That is pretty intense': './presets/Hexcollie_ Krash_ Inventive software n Pithlit - That is pretty intense.json',
  'Hexcollie_ Rova n EOS - Flatliner _flexi shaded2_': './presets/Hexcollie_ Rova n EOS - Flatliner _flexi shaded2_.json',
  'Hexcollie_ Rova n EOS - Flatliner': './presets/Hexcollie_ Rova n EOS - Flatliner.json',
  'Hexcollie_ Rova n EOS - In or Out': './presets/Hexcollie_ Rova n EOS - In or Out.json',
  'Hexcollie_ Zylot n Phat - It has to be wrong to have this much fun without any talent': './presets/Hexcollie_ Zylot n Phat - It has to be wrong to have this much fun without any talent.json',
  'Idiot - 9-7-02 _Remix 2_': './presets/Idiot - 9-7-02 _Remix 2_.json',
  'idiot - Back in the game': './presets/idiot - Back in the game.json',
  'idiot - Forty Six and 2 _pushit__': './presets/idiot - Forty Six and 2 _pushit__.json',
  'idiot - Great Tulip Majesty _txtr wrap_': './presets/idiot - Great Tulip Majesty _txtr wrap_.json',
  'idiot - Great Tulip Majesty': './presets/idiot - Great Tulip Majesty.json',
  'Idiot - Marphets Surreal Dream _Hypnotic Spiral Mix_': './presets/Idiot - Marphets Surreal Dream _Hypnotic Spiral Mix_.json',
  'Idiot24-7-gohtsthirdeye': './presets/Idiot24-7-gohtsthirdeye.json',
  'Idiot24-7-mindbender7_superbendmix1_': './presets/Idiot24-7-mindbender7_superbendmix1_.json',
  'Illusion _ Unchained - New Strategy': './presets/Illusion _ Unchained - New Strategy.json',
  'InCUbuS - Our Destiny': './presets/InCUbuS - Our Destiny.json',
  'Jc - Life': './presets/Jc - Life.json',
  'Jc - Lungs': './presets/Jc - Lungs.json',
  'Krash - Snowflake Halo': './presets/Krash - Snowflake Halo.json',
  'Krash and Fvese - Molten Indecision _Fvese Remix_': './presets/Krash and Fvese - Molten Indecision _Fvese Remix_.json',
  'Krash and Rovastar - Rainbow Orb 2 Peacock _Sumpkin Tweak_': './presets/Krash and Rovastar - Rainbow Orb 2 Peacock _Sumpkin Tweak_.json',
  'Krash and Zylot - Snowflake Halo _Ice Cube mix_': './presets/Krash and Zylot - Snowflake Halo _Ice Cube mix_.json',
  'Krash _ yin - Electric universe _nuclear secrets_ _Phat_Carbon_mix_': './presets/Krash _ yin - Electric universe _nuclear secrets_ _Phat_Carbon_mix_.json',
  'Krash _ yin - Electric universe _nuclear secrets_ _Phat_nuleus_mix_': './presets/Krash _ yin - Electric universe _nuclear secrets_ _Phat_nuleus_mix_.json',
  'Krash _ yin - Electric universe _uncertainty principle_': './presets/Krash _ yin - Electric universe _uncertainty principle_.json',
  'Krash _ yin - Electric universe _variable spin - 004_': './presets/Krash _ yin - Electric universe _variable spin - 004_.json',
  'Krash _ yin - Electric universe _variable spin_': './presets/Krash _ yin - Electric universe _variable spin_.json',
  'Krash _ yin _ Phat - Electric universe _uncertainty principle__remix': './presets/Krash _ yin _ Phat - Electric universe _uncertainty principle__remix.json',
  'Krash _ yin _ Phat - Electric universe _uncertainty principle__remix_v2': './presets/Krash _ yin _ Phat - Electric universe _uncertainty principle__remix_v2.json',
  'Krash _ yin _ Phat - Electric universe _uncertainty principle__unknown_mix': './presets/Krash _ yin _ Phat - Electric universe _uncertainty principle__unknown_mix.json',
  'Lightspeed-dune2': './presets/Lightspeed-dune2.json',
  'Lightspeed-dune3': './presets/Lightspeed-dune3.json',
  'Liquido': './presets/Liquido.json',
  'LuxXx - Fuck ur Fractal Muscles I': './presets/LuxXx - Fuck ur Fractal Muscles I.json',
  'LuxXx - Fuck ur Fractal Muscles II': './presets/LuxXx - Fuck ur Fractal Muscles II.json',
  'mega swirl': './presets/mega swirl.json',
  'Microcosm': './presets/Microcosm.json',
  'Mind of Zigrot': './presets/Mind of Zigrot.json',
  'Mr_Zoolook - Hypnodisc': './presets/Mr_Zoolook - Hypnodisc.json',
  'Mr_Zoolook - Pinwheel _reactive_': './presets/Mr_Zoolook - Pinwheel _reactive_.json',
  'Mstress - Aurora Boreale': './presets/Mstress - Aurora Boreale.json',
  'Mstress - Color Eater _Static Mix_': './presets/Mstress - Color Eater _Static Mix_.json',
  'Mstress - Color Rain': './presets/Mstress - Color Rain.json',
  'Mstress - Quiet Lake3': './presets/Mstress - Quiet Lake3.json',
  'Mstress and Zylot - Trapped Ball _Rainbow Mix_': './presets/Mstress and Zylot - Trapped Ball _Rainbow Mix_.json',
  'Mstress-curtain': './presets/Mstress-curtain.json',
  'New _Indecision Code_': './presets/New _Indecision Code_.json',
  'NiGHtHawK - Eye of Gawd_Phat_Spiral_edit': './presets/NiGHtHawK - Eye of Gawd_Phat_Spiral_edit.json',
  'NiGHtHawK - Eye of Gawd_Phat_Spiral_edit_v2': './presets/NiGHtHawK - Eye of Gawd_Phat_Spiral_edit_v2.json',
  'NiGHtHawK - Eye of Gawd_Phat_Stationary_Edit': './presets/NiGHtHawK - Eye of Gawd_Phat_Stationary_Edit.json',
  'Northern Lights Bud': './presets/Northern Lights Bud.json',
  'Northern Lights II': './presets/Northern Lights II.json',
  'Northern Lights Throbbing Bud': './presets/Northern Lights Throbbing Bud.json',
  'Northern Lights': './presets/Northern Lights.json',
  'Ondras - Eruptions': './presets/Ondras - Eruptions.json',
  'Ondras - Matrix Blockout _Total Lolipop Remixx_': './presets/Ondras - Matrix Blockout _Total Lolipop Remixx_.json',
  'Ondras - Radar': './presets/Ondras - Radar.json',
  'ORB - Acid in my eyes': './presets/ORB - Acid in my eyes.json',
  'ORB - Black hole sun moon': './presets/ORB - Black hole sun moon.json',
  'ORB - Blowtorch chill': './presets/ORB - Blowtorch chill.json',
  'ORB - Blowtorch': './presets/ORB - Blowtorch.json',
  'ORB - Carpet Bomb': './presets/ORB - Carpet Bomb.json',
  'ORB - Cloud Scope': './presets/ORB - Cloud Scope.json',
  'ORB - Cosmic Dream': './presets/ORB - Cosmic Dream.json',
  'ORB - Deadly tile grout form hell': './presets/ORB - Deadly tile grout form hell.json',
  'ORB - Eat me': './presets/ORB - Eat me.json',
  'ORB - Eye of time': './presets/ORB - Eye of time.json',
  'ORB - Fire and Fumes 2': './presets/ORB - Fire and Fumes 2.json',
  'ORB - Fire Poi 2': './presets/ORB - Fire Poi 2.json',
  'ORB - Fire Poi': './presets/ORB - Fire Poi.json',
  'ORB - Going nowhere': './presets/ORB - Going nowhere.json',
  'ORB - Hippie Tornado': './presets/ORB - Hippie Tornado.json',
  'ORB - Kalidescope': './presets/ORB - Kalidescope.json',
  'ORB - Lost Time Symertic': './presets/ORB - Lost Time Symertic.json',
  'ORB - Lost Time': './presets/ORB - Lost Time.json',
  'ORB - Lost To Much Time': './presets/ORB - Lost To Much Time.json',
  'ORB - Mega Spectrum': './presets/ORB - Mega Spectrum.json',
  'ORB - Mental jellyfish': './presets/ORB - Mental jellyfish.json',
  'ORB - Radiation': './presets/ORB - Radiation.json',
  'ORB - Radiation2': './presets/ORB - Radiation2.json',
  'ORB - Saturns Rings': './presets/ORB - Saturns Rings.json',
  'ORB - Snapshot': './presets/ORB - Snapshot.json',
  'ORB - Solar Radiation': './presets/ORB - Solar Radiation.json',
  'ORB - Solar Sail': './presets/ORB - Solar Sail.json',
  'ORB - Space Time2': './presets/ORB - Space Time2.json',
  'ORB - Split Atom': './presets/ORB - Split Atom.json',
  'ORB - Starflower blazing sun': './presets/ORB - Starflower blazing sun.json',
  'ORB - Starflower diff tracking': './presets/ORB - Starflower diff tracking.json',
  'ORB - Toy snakes hectic': './presets/ORB - Toy snakes hectic.json',
  'ORB - Toy snakes sleepy': './presets/ORB - Toy snakes sleepy.json',
  'ORB - Toy Snakes Starry Night': './presets/ORB - Toy Snakes Starry Night.json',
  'ORB - Toy snakes ultimate': './presets/ORB - Toy snakes ultimate.json',
  'ORB - Wheel of Fire': './presets/ORB - Wheel of Fire.json',
  'ORB - Windmill and Water': './presets/ORB - Windmill and Water.json',
  'ORB - Windmill': './presets/ORB - Windmill.json',
  'ORB - Xenon': './presets/ORB - Xenon.json',
  'ORB swirl tunnel': './presets/ORB swirl tunnel.json',
  'Orbasonic': './presets/Orbasonic.json',
  'Phat _ Emale - best halfbaked reversed _Remix_': './presets/Phat _ Emale - best halfbaked reversed _Remix_.json',
  'Phat-Zoom artifacts': './presets/Phat-Zoom artifacts.json',
  'Phat-Zoom artifacts_v2': './presets/Phat-Zoom artifacts_v2.json',
  'Phat_Aderrasi - Chromatic Abyss _the other side__Dope': './presets/Phat_Aderrasi - Chromatic Abyss _the other side__Dope.json',
  'Phat_Aderrasi - Chromatic Abyss _the other side__Dope2': './presets/Phat_Aderrasi - Chromatic Abyss _the other side__Dope2.json',
  'Phat_Aderrasi - Chromatic Abyss _the other side__PhatColours3': './presets/Phat_Aderrasi - Chromatic Abyss _the other side__PhatColours3.json',
  'Phat_Aderrasi - Chromatic Abyss _the other side__PhatColours6': './presets/Phat_Aderrasi - Chromatic Abyss _the other side__PhatColours6.json',
  'Phat_Aderrasi - Chromatic Abyss _the other side__PhatColours__what_s this': './presets/Phat_Aderrasi - Chromatic Abyss _the other side__PhatColours__what_s this.json',
  'Phat_Aderrasi - Chromatic Abyss _the other side__remix': './presets/Phat_Aderrasi - Chromatic Abyss _the other side__remix.json',
  'Phat_fiShbRaiN_Looker': './presets/Phat_fiShbRaiN_Looker.json',
  'Phat_fiShbRaiN_Mandala_Bare_No_Border_mix': './presets/Phat_fiShbRaiN_Mandala_Bare_No_Border_mix.json',
  'phat_Phenethylamine': './presets/phat_Phenethylamine.json',
  'phat_RippleNebula7': './presets/phat_RippleNebula7.json',
  'phat_RippleNebula9': './presets/phat_RippleNebula9.json',
  'phat_RippleNebula99': './presets/phat_RippleNebula99.json',
  'phat_RippleNebula_update': './presets/phat_RippleNebula_update.json',
  'Phat_Rovastar - 1337 boxes': './presets/Phat_Rovastar - 1337 boxes.json',
  'Phat_Rovastar - 1337 boxes3': './presets/Phat_Rovastar - 1337 boxes3.json',
  'Phat_Rovastar - What_does_your_soul_look_like': './presets/Phat_Rovastar - What_does_your_soul_look_like.json',
  'Phat_Rovastar - What_does_your_soul_look_like2': './presets/Phat_Rovastar - What_does_your_soul_look_like2.json',
  'Phat_Rovastar - What_does_your_soul_look_like3': './presets/Phat_Rovastar - What_does_your_soul_look_like3.json',
  'Phat_Rovastar - What_does_your_soul_look_like4': './presets/Phat_Rovastar - What_does_your_soul_look_like4.json',
  'Phat_Rovastar - What_does_your_soul_look_like5': './presets/Phat_Rovastar - What_does_your_soul_look_like5.json',
  'Phat_Rovastar - What_does_your_soul_look_like7': './presets/Phat_Rovastar - What_does_your_soul_look_like7.json',
  'Phat_Rovastar - What_does_your_soul_look_like8': './presets/Phat_Rovastar - What_does_your_soul_look_like8.json',
  'Phat_Rovastar - What_does_your_soul_look_like9': './presets/Phat_Rovastar - What_does_your_soul_look_like9.json',
  'Phat_Rovastar - What_does_your_soul_look_like9b': './presets/Phat_Rovastar - What_does_your_soul_look_like9b.json',
  'Phat_shifter - Angel': './presets/Phat_shifter - Angel.json',
  'Phat_shifter - Angel2': './presets/Phat_shifter - Angel2.json',
  'Phat_shifter - Angel3': './presets/Phat_shifter - Angel3.json',
  'Phat_shifter - Angel4': './presets/Phat_shifter - Angel4.json',
  'Phat_shifter - sinkhole web_remix': './presets/Phat_shifter - sinkhole web_remix.json',
  'Phat_TanSpiral': './presets/Phat_TanSpiral.json',
  'Phat_Zylot - Will_o Wisp _Adult_remix': './presets/Phat_Zylot - Will_o Wisp _Adult_remix.json',
  'Phmall - Mayan Sunrize _y_': './presets/Phmall - Mayan Sunrize _y_.json',
  'PieturP - caleidos_sick': './presets/PieturP - caleidos_sick.json',
  'PieturP - caleidos_sick2': './presets/PieturP - caleidos_sick2.json',
  'PieturP - circles_progressive': './presets/PieturP - circles_progressive.json',
  'PieturP - HSL-here-we-go-2': './presets/PieturP - HSL-here-we-go-2.json',
  'PieturP - HSL-here-we-go-3': './presets/PieturP - HSL-here-we-go-3.json',
  'PieturP - HSL-here-we-go-4': './presets/PieturP - HSL-here-we-go-4.json',
  'PieturP - HSL-here-we-go-circle': './presets/PieturP - HSL-here-we-go-circle.json',
  'PieturP - HSL-here-we-go-circles-weird': './presets/PieturP - HSL-here-we-go-circles-weird.json',
  'PieturP - HSL-here-we-go-circles': './presets/PieturP - HSL-here-we-go-circles.json',
  'PieturP - HSL-tunnelvisions': './presets/PieturP - HSL-tunnelvisions.json',
  'PieturP - HSL-tunnelvisions_morphing': './presets/PieturP - HSL-tunnelvisions_morphing.json',
  'PieturP - HSL-tunnelvisions_morphing2': './presets/PieturP - HSL-tunnelvisions_morphing2.json',
  'PieturP - HSL-tunnelvisions_morphing3': './presets/PieturP - HSL-tunnelvisions_morphing3.json',
  'PieturP - HSLtoRGB-swirl': './presets/PieturP - HSLtoRGB-swirl.json',
  'PieturP - sides_betterSeries1': './presets/PieturP - sides_betterSeries1.json',
  'PieturP - sides_betterSeries2_absurd': './presets/PieturP - sides_betterSeries2_absurd.json',
  'PieturP - sides_betterSeries2_def': './presets/PieturP - sides_betterSeries2_def.json',
  'PieturP - sides_betterSeries3': './presets/PieturP - sides_betterSeries3.json',
  'PieturP - sides_betterSeries3_solarised': './presets/PieturP - sides_betterSeries3_solarised.json',
  'PieturP - stripes-goingFastMix': './presets/PieturP - stripes-goingFastMix.json',
  'PieturP - stripes-goingSlowMix': './presets/PieturP - stripes-goingSlowMix.json',
  'PieturP - stripes-hippiestyle': './presets/PieturP - stripes-hippiestyle.json',
  'PieturP - stripes-tvstyle': './presets/PieturP - stripes-tvstyle.json',
  'PieturP - sunflare': './presets/PieturP - sunflare.json',
  'PieturP - sunflare2': './presets/PieturP - sunflare2.json',
  'PieturP - triptrap__crazed-perspective-mix_': './presets/PieturP - triptrap__crazed-perspective-mix_.json',
  'Pinbi7 _ Fvese - Definitly Not For The Epileptic 1': './presets/Pinbi7 _ Fvese - Definitly Not For The Epileptic 1.json',
  'Pinbi7 _ Fvese - Definitly Not For The Epileptic 2': './presets/Pinbi7 _ Fvese - Definitly Not For The Epileptic 2.json',
  'Pinbi7 _ Fvese - Definitly Not For The Epileptic 3': './presets/Pinbi7 _ Fvese - Definitly Not For The Epileptic 3.json',
  'Pinbi7 _ Idiot - Cathedral': './presets/Pinbi7 _ Idiot - Cathedral.json',
  'Pinbi7 _ Idiot - Get Sucked In': './presets/Pinbi7 _ Idiot - Get Sucked In.json',
  'Pinbi7 _ Rocke - super star': './presets/Pinbi7 _ Rocke - super star.json',
  'Pinbi7_fvese-hyperspace': './presets/Pinbi7_fvese-hyperspace.json',
  'Pinbi7_fvese-hypnoticflower': './presets/Pinbi7_fvese-hypnoticflower.json',
  'Pinbi7_fvese-intotheunknown': './presets/Pinbi7_fvese-intotheunknown.json',
  'Pinbi7_Fvese-NotForTheEpilepti': './presets/Pinbi7_Fvese-NotForTheEpilepti.json',
  'Pinbi7_stuttler-trackdown': './presets/Pinbi7_stuttler-trackdown.json',
  'Pithlit - Distorted': './presets/Pithlit - Distorted.json',
  'Pithlit - Golden Rays': './presets/Pithlit - Golden Rays.json',
  'Pithlit - Hyperspace': './presets/Pithlit - Hyperspace.json',
  'Pithlit - Nova': './presets/Pithlit - Nova.json',
  'Pithlit - Nova_Rainbow mix_': './presets/Pithlit - Nova_Rainbow mix_.json',
  'Pithlit - Whirlpool': './presets/Pithlit - Whirlpool.json',
  'Rainbow Deflection 2': './presets/Rainbow Deflection 2.json',
  'raron - simple frequency spectrum 3': './presets/raron - simple frequency spectrum 3.json',
  'raron - simple frequency spectrum_ clouds vertical scroll - 777': './presets/raron - simple frequency spectrum_ clouds vertical scroll - 777.json',
  'Redi Jedi - Shaking your reality': './presets/Redi Jedi - Shaking your reality.json',
  'Redi Jedi - Time travling through a traffic jam': './presets/Redi Jedi - Time travling through a traffic jam.json',
  'Redi Jedi - wheres the beef': './presets/Redi Jedi - wheres the beef.json',
  'Redi Jedi - your radar may have a few kinks in it': './presets/Redi Jedi - your radar may have a few kinks in it.json',
  'Redi Jedi - Your tv is not broken': './presets/Redi Jedi - Your tv is not broken.json',
  'Roadkill Diner': './presets/Roadkill Diner.json',
  'Rocke - Personal Comet': './presets/Rocke - Personal Comet.json',
  'Roosta  - Bursting': './presets/Roosta  - Bursting.json',
  'Roosta - A Fractured Reflection': './presets/Roosta - A Fractured Reflection.json',
  'Roosta - A Gateway is Expressed - Show Me the Way': './presets/Roosta - A Gateway is Expressed - Show Me the Way.json',
  'Roosta - A Gateway is Expressed': './presets/Roosta - A Gateway is Expressed.json',
  'Roosta - Cerebral Overload': './presets/Roosta - Cerebral Overload.json',
  'Roosta - Diaspora - Central Fire Mix': './presets/Roosta - Diaspora - Central Fire Mix.json',
  'Roosta - Galactic Introspection - Solar flare mix': './presets/Roosta - Galactic Introspection - Solar flare mix.json',
  'Roosta - Galactic Introspection': './presets/Roosta - Galactic Introspection.json',
  'Roosta - Jagged Pulse': './presets/Roosta - Jagged Pulse.json',
  'Roosta - Marks The Spot': './presets/Roosta - Marks The Spot.json',
  'Roosta - Shine_ Spiral_ Shine_ - High Gamma': './presets/Roosta - Shine_ Spiral_ Shine_ - High Gamma.json',
  'Roosta - Shine_ Spiral_ Shine_': './presets/Roosta - Shine_ Spiral_ Shine_.json',
  'Rovastar - Blue Shining': './presets/Rovastar - Blue Shining.json',
  'Rovastar - Dark Ritual _NEOhm_s _Bat_-BlackBack-SuperMegaUltraForceSpaceDuel-mix_': './presets/Rovastar - Dark Ritual _NEOhm_s _Bat_-BlackBack-SuperMegaUltraForceSpaceDuel-mix_.json',
  'Rovastar - Dark Ritual _Star Of Destiny Denied Mix_': './presets/Rovastar - Dark Ritual _Star Of Destiny Denied Mix_.json',
  'Rovastar - Destiny Star _Starbrust Mix_': './presets/Rovastar - Destiny Star _Starbrust Mix_.json',
  'Rovastar - Explosive Minds': './presets/Rovastar - Explosive Minds.json',
  'Rovastar - Fractopia _Galaxy Swirl Mix 2_': './presets/Rovastar - Fractopia _Galaxy Swirl Mix 2_.json',
  'Rovastar - Harlequin_s Liquid Dragon': './presets/Rovastar - Harlequin_s Liquid Dragon.json',
  'Rovastar - Hyperspace _Hyper Speed Mix_': './presets/Rovastar - Hyperspace _Hyper Speed Mix_.json',
  'Rovastar - Hyperspace': './presets/Rovastar - Hyperspace.json',
  'Rovastar - Kronos_ Twisted Spawn': './presets/Rovastar - Kronos_ Twisted Spawn.json',
  'Rovastar - Mosaics Of Ages': './presets/Rovastar - Mosaics Of Ages.json',
  'Rovastar - Northern Lights': './presets/Rovastar - Northern Lights.json',
  'Rovastar - Oozing Resistance': './presets/Rovastar - Oozing Resistance.json',
  'Rovastar - Parallel Universe': './presets/Rovastar - Parallel Universe.json',
  'Rovastar - Parallelogram Bin 2 _Naked Mix_': './presets/Rovastar - Parallelogram Bin 2 _Naked Mix_.json',
  'Rovastar - Parallelogram Bin 2': './presets/Rovastar - Parallelogram Bin 2.json',
  'Rovastar - Shango 1': './presets/Rovastar - Shango 1.json',
  'Rovastar - Snapshot Of Space': './presets/Rovastar - Snapshot Of Space.json',
  'Rovastar - Space _Twisted Dimension Mix_': './presets/Rovastar - Space _Twisted Dimension Mix_.json',
  'Rovastar - Space': './presets/Rovastar - Space.json',
  'Rovastar - Throbbing Northern Lights': './presets/Rovastar - Throbbing Northern Lights.json',
  'Rovastar - Tripmaker _Space Trip Mix_': './presets/Rovastar - Tripmaker _Space Trip Mix_.json',
  'rovastar - Trippy Sperm': './presets/rovastar - Trippy Sperm.json',
  'Rovastar - Twilight Tunnel': './presets/Rovastar - Twilight Tunnel.json',
  'Rovastar - VooV_s Light Pattern': './presets/Rovastar - VooV_s Light Pattern.json',
  'Rovastar - VooV_s Naked Movement': './presets/Rovastar - VooV_s Naked Movement.json',
  'Rovastar - Voyage': './presets/Rovastar - Voyage.json',
  'Rovastar - Xeper_s Birth': './presets/Rovastar - Xeper_s Birth.json',
  'Rovastar and Fvese - Hyperspace Nightmare': './presets/Rovastar and Fvese - Hyperspace Nightmare.json',
  'Rovastar and idiot24-7 - Abstract Psychaos _dot wave_': './presets/Rovastar and idiot24-7 - Abstract Psychaos _dot wave_.json',
  'Rovastar and idiot24-7 - Abstract Psychaos': './presets/Rovastar and idiot24-7 - Abstract Psychaos.json',
  'Rovastar and Krash - Seas Of Tron': './presets/Rovastar and Krash - Seas Of Tron.json',
  'Rovastar _ Geiss - Dynamic Swirls 3 _Broken Destiny Mix_': './presets/Rovastar _ Geiss - Dynamic Swirls 3 _Broken Destiny Mix_.json',
  'Rovastar _ Idiot24-7 - Juanita': './presets/Rovastar _ Idiot24-7 - Juanita.json',
  'Rovastar _ Idiot24-7 - Marphet_s Shrine': './presets/Rovastar _ Idiot24-7 - Marphet_s Shrine.json',
  'Rovastar _ Krash - Hallucinogenic Pyramids _Beater Time Mix_': './presets/Rovastar _ Krash - Hallucinogenic Pyramids _Beater Time Mix_.json',
  'Rovastar _ Krash - Hallucinogenic Pyramids _Extra Beat Time Mix_': './presets/Rovastar _ Krash - Hallucinogenic Pyramids _Extra Beat Time Mix_.json',
  'Rovastar _ Loadus - FractalDrop _Active Sparks Mix_': './presets/Rovastar _ Loadus - FractalDrop _Active Sparks Mix_.json',
  'Rovastar _ Loadus _ Zylot - FractalDrop _Spark Machine_': './presets/Rovastar _ Loadus _ Zylot - FractalDrop _Spark Machine_.json',
  'Rovastar _ Malte - Circle Of Deeper Meaning': './presets/Rovastar _ Malte - Circle Of Deeper Meaning.json',
  'Rovastar _ Rocke - Sugar Spun Sister': './presets/Rovastar _ Rocke - Sugar Spun Sister.json',
  'Rovastar _ StudioMusic - Spider In the Mind': './presets/Rovastar _ StudioMusic - Spider In the Mind.json',
  'Rovastar _ StudioMusic - Spider_s Dance': './presets/Rovastar _ StudioMusic - Spider_s Dance.json',
  'Rovastar _ Unchained - Ambrosia Mystic _Dark Heart Mix_': './presets/Rovastar _ Unchained - Ambrosia Mystic _Dark Heart Mix_.json',
  'Rovastar _ Unchained - Further Tastes Of Ambrosia': './presets/Rovastar _ Unchained - Further Tastes Of Ambrosia.json',
  'Rovastar _ Unchained - Life After Pie _Remix_': './presets/Rovastar _ Unchained - Life After Pie _Remix_.json',
  'Rovastar _ Unchained - Orb Of Voodoo': './presets/Rovastar _ Unchained - Orb Of Voodoo.json',
  'Rovastar _ Unchained - Red Planet Exploration': './presets/Rovastar _ Unchained - Red Planet Exploration.json',
  'Rovastar _ Zylot - IMOC Invasion': './presets/Rovastar _ Zylot - IMOC Invasion.json',
  'Rovastar _ Zylot - Iouo Stone Morphic Fusion': './presets/Rovastar _ Zylot - Iouo Stone Morphic Fusion.json',
  'Rovastar _ Zylot - Reactor Mirage': './presets/Rovastar _ Zylot - Reactor Mirage.json',
  'Rovastar _ Zylot - Reactor Turmoil': './presets/Rovastar _ Zylot - Reactor Turmoil.json',
  'Rovastar-altarsofmadn2_frozentimemix_': './presets/Rovastar-altarsofmadn2_frozentimemix_.json',
  'Rovastar-voovsnakedmov_pincushionmix_': './presets/Rovastar-voovsnakedmov_pincushionmix_.json',
  'Rovastar_fvese-strangermin_astralmix_': './presets/Rovastar_fvese-strangermin_astralmix_.json',
  'Rozzor and Shreyas - Happy Hubris': './presets/Rozzor and Shreyas - Happy Hubris.json',
  'Rozzor vs Esotic - Pixie Party Light _Party Down_': './presets/Rozzor vs Esotic - Pixie Party Light _Party Down_.json',
  'Rozzor vs Esotic - Pixie Party Light _With Liquid Refreshment_ Bonus Round': './presets/Rozzor vs Esotic - Pixie Party Light _With Liquid Refreshment_ Bonus Round.json',
  'Rozzor vs Esotic - Pixie Party Light _With Liquid Refreshment_': './presets/Rozzor vs Esotic - Pixie Party Light _With Liquid Refreshment_.json',
  'Rozzor _ Esotic - Pixie Party Light _Party Down Mix_': './presets/Rozzor _ Esotic - Pixie Party Light _Party Down Mix_.json',
  'Rozzor _ Esotic - PPL _NWI_ Mandala Chill Color Reactive Texture Tweaked': './presets/Rozzor _ Esotic - PPL _NWI_ Mandala Chill Color Reactive Texture Tweaked.json',
  'Rozzor _ Esotic - PPL _NWI_ Mandala Chill Color Reactive': './presets/Rozzor _ Esotic - PPL _NWI_ Mandala Chill Color Reactive.json',
  'Rozzor _ Neuro - Starover _Semicolon Mix_': './presets/Rozzor _ Neuro - Starover _Semicolon Mix_.json',
  'shifter - blueshift _slush_': './presets/shifter - blueshift _slush_.json',
  'shifter - blueshift': './presets/shifter - blueshift.json',
  'shifter - brain coral cartoon': './presets/shifter - brain coral cartoon.json',
  'shifter - brain coral flip': './presets/shifter - brain coral flip.json',
  'shifter - brain coral primaries': './presets/shifter - brain coral primaries.json',
  'shifter - brain coral static A': './presets/shifter - brain coral static A.json',
  'shifter - brain coral static B': './presets/shifter - brain coral static B.json',
  'shifter - brain coral _left brained_': './presets/shifter - brain coral _left brained_.json',
  'shifter - brain coral _non-inverted_': './presets/shifter - brain coral _non-inverted_.json',
  'shifter - brain coral': './presets/shifter - brain coral.json',
  'shifter - catseye sexy sataniq fuqre': './presets/shifter - catseye sexy sataniq fuqre.json',
  'shifter - comets': './presets/shifter - comets.json',
  'shifter - crosshatch colony beta6': './presets/shifter - crosshatch colony beta6.json',
  'shifter - crosshatch neopsy': './presets/shifter - crosshatch neopsy.json',
  'shifter - curlique': './presets/shifter - curlique.json',
  'shifter - cyanred': './presets/shifter - cyanred.json',
  'shifter - digi': './presets/shifter - digi.json',
  'shifter - feathers _angel wings__phat_Updated_Ugly_colors_remix': './presets/shifter - feathers _angel wings__phat_Updated_Ugly_colors_remix.json',
  'shifter - feathers _wings_': './presets/shifter - feathers _wings_.json',
  'shifter - firefrost': './presets/shifter - firefrost.json',
  'shifter - flashburn v2': './presets/shifter - flashburn v2.json',
  'shifter - fractal grinder _fractured smoke_': './presets/shifter - fractal grinder _fractured smoke_.json',
  'shifter - fractal grinder _opalescent_': './presets/shifter - fractal grinder _opalescent_.json',
  'shifter - fractal grinder': './presets/shifter - fractal grinder.json',
  'shifter - fuzzball _implosion_': './presets/shifter - fuzzball _implosion_.json',
  'shifter - fuzzball_1': './presets/shifter - fuzzball_1.json',
  'shifter - glassworms flare': './presets/shifter - glassworms flare.json',
  'shifter - glassworms flare_1': './presets/shifter - glassworms flare_1.json',
  'shifter - glassworms flip': './presets/shifter - glassworms flip.json',
  'shifter - glassworms multi': './presets/shifter - glassworms multi.json',
  'shifter - glassworms original': './presets/shifter - glassworms original.json',
  'shifter - glassworms skip': './presets/shifter - glassworms skip.json',
  'shifter - glassworms skip_phat_edit': './presets/shifter - glassworms skip_phat_edit.json',
  'shifter - glassworms trio': './presets/shifter - glassworms trio.json',
  'shifter - glassworms trip': './presets/shifter - glassworms trip.json',
  'shifter - ice ripples': './presets/shifter - ice ripples.json',
  'shifter - kinderkind neon': './presets/shifter - kinderkind neon.json',
  'shifter - lattice _eclipse_': './presets/shifter - lattice _eclipse_.json',
  'shifter - lattice': './presets/shifter - lattice.json',
  'shifter - lazerspecs': './presets/shifter - lazerspecs.json',
  'shifter - lazerspecs_phat_edit': './presets/shifter - lazerspecs_phat_edit.json',
  'shifter - mandala': './presets/shifter - mandala.json',
  'shifter - neon pulse _reactive_': './presets/shifter - neon pulse _reactive_.json',
  'shifter - neon pulse': './presets/shifter - neon pulse.json',
  'shifter - open the light': './presets/shifter - open the light.json',
  'shifter - orthoganal light niobium': './presets/shifter - orthoganal light niobium.json',
  'shifter - orthoganal light': './presets/shifter - orthoganal light.json',
  'shifter - phasm candystripe': './presets/shifter - phasm candystripe.json',
  'shifter - phasm gaseous': './presets/shifter - phasm gaseous.json',
  'shifter - phasm inksplot': './presets/shifter - phasm inksplot.json',
  'shifter - phasm slick _fps_ mix_': './presets/shifter - phasm slick _fps_ mix_.json',
  'shifter - phasm wraith _fps_ mix_': './presets/shifter - phasm wraith _fps_ mix_.json',
  'shifter - phasm wraith': './presets/shifter - phasm wraith.json',
  'shifter - phasm': './presets/shifter - phasm.json',
  'shifter - pinwheel': './presets/shifter - pinwheel.json',
  'shifter - plasmic fact': './presets/shifter - plasmic fact.json',
  'shifter - plasmic': './presets/shifter - plasmic.json',
  'shifter - ralter oilslick b': './presets/shifter - ralter oilslick b.json',
  'shifter - rapid birth bright': './presets/shifter - rapid birth bright.json',
  'shifter - rapid birth': './presets/shifter - rapid birth.json',
  'shifter - rececho': './presets/shifter - rececho.json',
  'shifter - simple spasm': './presets/shifter - simple spasm.json',
  'shifter - sinkhole web': './presets/shifter - sinkhole web.json',
  'shifter - snakeskin _edged_': './presets/shifter - snakeskin _edged_.json',
  'shifter - snakeskin _pulse mini_': './presets/shifter - snakeskin _pulse mini_.json',
  'shifter - snakeskin': './presets/shifter - snakeskin.json',
  'shifter - spasmic comet neon': './presets/shifter - spasmic comet neon.json',
  'shifter - spectro': './presets/shifter - spectro.json',
  'shifter - spills blender _ krash beatdetect - mash0000 - here comb your hair with this planet': './presets/shifter - spills blender _ krash beatdetect - mash0000 - here comb your hair with this planet.json',
  'shifter - spincycle b': './presets/shifter - spincycle b.json',
  'shifter - spincycle c': './presets/shifter - spincycle c.json',
  'shifter - spincycle _soft candy_': './presets/shifter - spincycle _soft candy_.json',
  'shifter - spincycle _sweeet candy_ Studio Music tweak': './presets/shifter - spincycle _sweeet candy_ Studio Music tweak.json',
  'shifter - spincycle _sweeet candy_': './presets/shifter - spincycle _sweeet candy_.json',
  'shifter - spincycle': './presets/shifter - spincycle.json',
  'shifter - spun sugar': './presets/shifter - spun sugar.json',
  'shifter - swarm': './presets/shifter - swarm.json',
  'shifter - timepeice': './presets/shifter - timepeice.json',
  'shifter - tumbling cubes _ripples_ Phat_parallel_planes_mix': './presets/shifter - tumbling cubes _ripples_ Phat_parallel_planes_mix.json',
  'shifter - tumbling cubes _ripples_': './presets/shifter - tumbling cubes _ripples_.json',
  'shifter - tumbling cubes _ripples__phat_frame_rate_tweak': './presets/shifter - tumbling cubes _ripples__phat_frame_rate_tweak.json',
  'shifter - urchin kali b': './presets/shifter - urchin kali b.json',
  'shifter - urchin kali echos': './presets/shifter - urchin kali echos.json',
  'shifter - urchin kali mod': './presets/shifter - urchin kali mod.json',
  'shifter - urchin kali': './presets/shifter - urchin kali.json',
  'shifter - urchin mod': './presets/shifter - urchin mod.json',
  'shifter - urchin mod_1': './presets/shifter - urchin mod_1.json',
  'shifter - urchin': './presets/shifter - urchin.json',
  'shifter _ Aderrasi - Airhandler _Sadako_': './presets/shifter _ Aderrasi - Airhandler _Sadako_.json',
  'shifter _ fiShbRaiN - witchcraft _i_m melting_': './presets/shifter _ fiShbRaiN - witchcraft _i_m melting_.json',
  'Shifter-yak_yetanotherkaleidoscope_00': './presets/Shifter-yak_yetanotherkaleidoscope_00.json',
  'Shifter-yak_yetanotherkaleidoscope_01': './presets/Shifter-yak_yetanotherkaleidoscope_01.json',
  'Shifter-yak_yetanotherkaleidoscope_02': './presets/Shifter-yak_yetanotherkaleidoscope_02.json',
  'Shreyas _ Unchained - Deeper Aesthetics _Rozzor mashup_': './presets/Shreyas _ Unchained - Deeper Aesthetics _Rozzor mashup_.json',
  'Sjadoh - Fortune Teller': './presets/Sjadoh - Fortune Teller.json',
  'Snowflake Halo': './presets/Snowflake Halo.json',
  'Stahlregen - Bass Pulsing _Geometry Mix B_': './presets/Stahlregen - Bass Pulsing _Geometry Mix B_.json',
  'Stahlregen - Bass Pulsing _Geometry Mix_': './presets/Stahlregen - Bass Pulsing _Geometry Mix_.json',
  'Stahlregen - Do the Wave _V2_': './presets/Stahlregen - Do the Wave _V2_.json',
  'Stahlregen - Do the Wave': './presets/Stahlregen - Do the Wave.json',
  'Stahlregen - Dots _Pixels - Blocky_': './presets/Stahlregen - Dots _Pixels - Blocky_.json',
  'Stahlregen - Dots _Pixels - more blur_': './presets/Stahlregen - Dots _Pixels - more blur_.json',
  'Stahlregen - Dots _Pixels - no Blur_': './presets/Stahlregen - Dots _Pixels - no Blur_.json',
  'Stahlregen - Dots _Pixels - reactive blur_': './presets/Stahlregen - Dots _Pixels - reactive blur_.json',
  'Stahlregen - Dots _Pixels_': './presets/Stahlregen - Dots _Pixels_.json',
  'Stahlregen - Dots _Psychedelic Flower V2 - Corrupt_': './presets/Stahlregen - Dots _Psychedelic Flower V2 - Corrupt_.json',
  'stahlregen - dots _psychedelic flower v2_': './presets/stahlregen - dots _psychedelic flower v2_.json',
  'stahlregen - dots _psychedelic flower_': './presets/stahlregen - dots _psychedelic flower_.json',
  'Stahlregen - Eckshack_s Eyeball _popped eyeball mix_': './presets/Stahlregen - Eckshack_s Eyeball _popped eyeball mix_.json',
  'Stahlregen - Eckshack_s Eyeball': './presets/Stahlregen - Eckshack_s Eyeball.json',
  'stahlregen - old school_ baby_ _spiral ornament_': './presets/stahlregen - old school_ baby_ _spiral ornament_.json',
  'Stahlregen - Old school_ baby_ _Spiral Ornament__1': './presets/Stahlregen - Old school_ baby_ _Spiral Ornament__1.json',
  'Stahlregen - Spiral Beats _Bigger__2': './presets/Stahlregen - Spiral Beats _Bigger__2.json',
  'stahlregen - spiral beats': './presets/stahlregen - spiral beats.json',
  'Stahlregen - Spiral Beats_1': './presets/Stahlregen - Spiral Beats_1.json',
  'Stahlregen - Spiral _Fugly_': './presets/Stahlregen - Spiral _Fugly_.json',
  'stahlregen - spiral _oh god my eyes_ it burns_ 2_': './presets/stahlregen - spiral _oh god my eyes_ it burns_ 2_.json',
  'Stahlregen - Spiral _Oh god my eyes_ it burns_ 3__1': './presets/Stahlregen - Spiral _Oh god my eyes_ it burns_ 3__1.json',
  'Stahlregen - Spiral _Oh god my eyes_ it burns__': './presets/Stahlregen - Spiral _Oh god my eyes_ it burns__.json',
  'Stahlregen - Spiral': './presets/Stahlregen - Spiral.json',
  'Stahlregen - Treb Spectre': './presets/Stahlregen - Treb Spectre.json',
  'Stahlregen - Wavering Flower _wtf mosaique_': './presets/Stahlregen - Wavering Flower _wtf mosaique_.json',
  'Stahlregen - Windmill _basic ethereal slipstream_': './presets/Stahlregen - Windmill _basic ethereal slipstream_.json',
  'Stahlregen - Windmill _basic_': './presets/Stahlregen - Windmill _basic_.json',
  'Stahlregen _ Unchained - Dot Kung Fu _Psychedelic Flower V2 - Corrupt_': './presets/Stahlregen _ Unchained - Dot Kung Fu _Psychedelic Flower V2 - Corrupt_.json',
  'Stuttler - Kaleidoscope From Hell': './presets/Stuttler - Kaleidoscope From Hell.json',
  'suksma - ed geining hateops': './presets/suksma - ed geining hateops.json',
  'suksma - gee zeus ov gaellilee': './presets/suksma - gee zeus ov gaellilee.json',
}

export async function getPresets(options?: GetPresetOptions): Promise<Presets> {
  const { name, random } = options || {}
  let count: number | undefined = options?.count
  if (count !== undefined && (typeof count !== 'number' || count < 1)) {
    throw new Error('Invalid count')
  }
  else if (count !== undefined && count > Object.keys(presetPaths).length) {
    count = Object.keys(presetPaths).length
  }

  if (name) {
    const presetData = await import(presetPaths[name])
    return { [name]: presetData }
  }

  const presetNames = Object.keys(presetPaths)

  if (random) {
    const shuffled = [...presetNames].sort(() => Math.random() - 0.5)
    const selectedNames = count ? shuffled.slice(0, count) : shuffled
    const result: Presets = {}
    for (const name of selectedNames) {
      result[name] = await import(presetPaths[name])
    }
    return result
  }
  else {
    const result: Presets = {}
    for (const name of count ? presetNames.slice(0, count) : presetNames) {
      result[name] = await import(presetPaths[name])
    }
    return result
  }
}
